### ISSUE TITLE
Errors when Attack Helicopter starts shooting: heliEventAttackHitOnIsoGameCharacter

### ISSUE THREAD

**Issue by boujuan** [TEHE-Studios/ExpandedHelicopterEvents#171] opened 2023-05-04 20:14 UTC
**Describe the bug**
When the attack helicopter spawns and starts shooting (allegedly to zombies), a large quantity of errors start amounting in our co-op server. It is heavily modded but I cant identify any incompatibilities.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Console logs:**
[console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/11401174/console.txt)
[coop-console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/11401175/coop-console.txt)

**Additional context**
Seems similar to this issue posted here as closed: https://github.com/TEHE-Studios/ExpandedHelicopterEvents/issues/145

**Comment by ChuckTheSheep** [comment] 2023-05-04 21:32
Duplicate of the one you linked #145, which is a duplicate of #139.

**Closed by ChuckTheSheep** 2023-05-04 21:32 UTC
Labels: bug
