### ISSUE TITLE
Sound loop issue

### ISSUE THREAD

**Issue by S4vrk** [TEHE-Studios/ExpandedHelicopterEvents#105] opened 2023-01-25 09:53 UTC
**Describe the bug**
Whenever on a multiplayer server, the player that isn't the host has this bug of sounds like planes flying ahead, air raid sirens never stopping.
This is only fixed with a rejoin, until a sound happens again.

**To Reproduce**
Start a server with this mod in multiplayer with someone else, wait for a plane to fly overhead, it has a chance for the sound to never end.

**Comment by ChuckTheSheep** [comment] 2023-01-26 03:16
Duplicate of #85

**Closed by ChuckTheSheep** 2023-01-26 03:16 UTC
Labels: bug
