### ISSUE TITLE
Unli Spam on logs

### ISSUE THREAD

**Issue by Jhezreel708** [TEHE-Studios/ExpandedHelicopterEvents#239] opened 2023-09-30 21:39 UTC
**Describe the bug**
Console Spamming of unable to find target making our logs grow to about 14gb.

**To Reproduce**
Simply have some players online and run the server for a long time once it has failed to find a player it will keep looping console making thousands of messages per second.

**Expected behavior**
Only one schedule and it should stop?

**Screenshots**

**Console logs:**
Console logs are stored in your local files. `OS:\Users\<username>\Zomboid\console.txt`
For single player (or connected players) the file is named `console.txt`, for hosts or servers the file will be named `coop-console` or `server-console`. *Include any relevant logs - do not cut or edit the log to make it smaller.*

**Additional context**

**Comment by Origichen** [comment] 2023-10-04 21:57
Yep, I've been having this same problem as well. I haven't gotten a solution from the authors yet but my temporary work around has been to disable all of the helicopters that can potentially attack.

**Comment by Chuckleberry-Finn** [comment] 2023-10-09 23:21
Duplicate of #233, which is more useful.

**Closed by Chuckleberry-Finn** 2023-10-09 23:21 UTC
Labels: bug
