### ISSUE TITLE
Got like 50 errors earlier when the helicopter was trying to shoot at me

### ISSUE THREAD

**Issue by Zakwb** [TEHE-Studios/ExpandedHelicopterEvents#145] opened 2023-03-21 22:59 UTC
**Describe the bug**
A clear and concise desI cription of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Console logs:**
Console logs are stored in your local files. `OS:\Users\<username>\Zomboid\console.txt`
For single player (or connected players) the file is named `console.txt`, for hosts or servers the file will be named `coop-console` or `server-console`. *Include any relevant logs - do not cut or edit the log to make it smaller.*

**Additional context**
[21-03-23_20-58-28_DebugLog.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/11034644/21-03-23_20-58-28_DebugLog.txt)

**Comment by ChuckTheSheep** [comment] 2023-03-22 12:20
Duplicate of #139
Will be fixed next update.

Thank you.

**Closed** 2023-03-22 12:21 UTC
Labels: bug, duplicate
