### ISSUE TITLE
In game client side error thrown on military heli spawn

### ISSUE THREAD

**Issue by Lhuani** [TEHE-Studios/ExpandedHelicopterEvents#197] opened 2023-07-12 16:57 UTC
I run a dedicated server and while sitting in my base at Louisville healing my wounds, a military helicopter spawned and threw the following repeated error in the clients side console. Dedicated server console did not throw any errors. The server is heavily moded and stable.

function: heliEventAttackHitOnIsoGameCharacter -- file: ExpandedHelicopter04b_AttackOnTarget.lua line # 55 | MOD: Expanded Helicopter Events
function: onServerCommand -- file: ExpandedHelicopter12b_OnServerToClientCommands.lua line # 216 | MOD: Expanded Helicopter Events

ERROR: General     , 1689180419941> 60,985,300> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: getHealth of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1689180419941> 60,985,300> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: getHealth of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)
	at zombie.network.GameClient.receiveClientCommand(GameClient.java:1513)
	at zombie.network.PacketTypes$PacketType.onMainLoopHandlePacketInternal(PacketTypes.java:1028)
	at zombie.network.GameClient.mainLoopHandlePacketInternal(GameClient.java:644)
	at zombie.network.GameClient.mainLoopDealWithNetData(GameClient.java:621)
	at zombie.network.GameClient.update(GameClient.java:431)
	at zombie.GameWindow.logic(GameWindow.java:232)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:765)
	at zombie.GameWindow.run_ez(GameWindow.java:667)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1689180419942> 60,985,301> -----------------------------------------
STACK TRACE

**Comment by Chuckleberry-Finn** [comment] 2023-07-13 11:02
dupe of #139

**Closed by Chuckleberry-Finn** 2023-07-13 11:02 UTC
Labels: bug, duplicate, fixed-pending-update
